tc39/proposal-weakrefs

specs/spec.md

WeakFactory constructor: Always set [[ActiveCells]] to an empty list (we add to it later).

Update spec.md: WeakFactory ctor fix

---

specs/spec.md

They do not have a [[WeakFactory]] internal slot.

WeakCell objects have a [[Factory]] internal slot

---

specs/spec.md

Without the escaping, it renders as `[Cleanup]` instead of `[[Cleanup]](iterator)`.

Escape open paren so that internal property is rendered correctly

---

spec/finalization-group.html
spec/weak-ref.html

These constructors' prototypes do not have any method which produces
a WeakRef or FinalizationGroup instance, so there's no need for them
to have this property.

Normative: Remove @@species from WeakRef and FinalizationGroup

---

spec/finalization-group.html

If undefined is passed it, it is treated as the lack of an unregisterToken.
If another primitive is used, then a TypeError is thrown, to avoid silent
misunderstandings.

Normative: unregisterToken must be an Object

---

spec/abstract-jobs.html

The specification already contains semantics here, but they are a bit obscure, so this patch adds a note that clarifies what happens. The issue was raised at https://bugs.chromium.org/p/v8/issues/detail?id=8179#c30

Editorial: Clarify that errors are not swallowed

---

README.md

Old specs was moved to `history` folder in #59 so we fix the old specs related links by changing folder from `specs` to `history`.

Fix history links

---

spec/abstract-jobs.html
spec/finalization-group.html

Leaking the iterator is bad as we could potentially cause the same holding to be iterated twice if the user iterates over a leaked iterator (from a previous turn) and a newly created iterator (in the following turn).
Fixes https://github.com/tc39/proposal-weakrefs/issues/29

Throw if FinalizationGroupCleanupIterator is iterated outside of the FinalizationGroupCleanupJob

---

spec/abstract-jobs.html

The cleanup job was renamed to `CleanupFinalizationGroup` but the objective section didn't get fully updated in #86.

Fix cleanup job name in Abstract Job's Objectives

---

README.md

In the IterableWeakMap example, the values() iterator may return values
that are no longer part of the map, because the iterator doesn't check
if the key is already collected.

Fix case in which IterableWeakMap keys() and values() could disagree

---

README.md

Incorporate discussion of turns into explainer

---

spec/finalization-group.html
spec/weak-ref.html

Reverts tc39/proposal-weakrefs#67
There are other mechanisms possible to make it easier to maintain certain virtualization shims, discussed in #22. This mechanism could be part of this proposal, part of another proposal, or implemented in JavaScript (as it is today). In any case, this mechanism could make it not longer needed to use the `System` object for the WeakRef and FinalizationGroup objects.

Revert "Move constructors to the System object"

---

spec/abstract-jobs.html

Editorial: `Call` takes a List as a third argument, not a scalar

---

spec/abstract-jobs.html
spec/finalization-group.html

- Don't add FinalizationGroup instances to the removed Agent Record's `[[FinalizationGroups]]`
- `DoAgentFinalization` no longer exists so it cannot call `CleanupFinalizationGroup`

Fix left-overs from layering changes in #86

---

spec/abstract-jobs.html

This attempts to address various issues with how reachability
is defined:
- If one WeakRef object points to an object, which points to
another one, the whole subgraph may be collected, as raised in
https://gist.github.com/jimblandy/0014dc11233d2d40df922af850b0489a
- An initial provisional definition of collectability is given:
>   No possible future execution of the program would observably
>   reference the object, except through a chain of references which
>   includes a [[Target]] field or [[Target]] internal slot.
This is intended to resolve #31 (by concluding that the impact on
host specifications is minimal, and spec graph reachability does not
imply liveness) and provide a starting point for #105
- The wording around 'field or internal slot' is clarified, resolving #115

Normative: Refine definition of reachability

---

spec/abstract-jobs.html
spec/weak-ref.html

This patch rephrases the definition of WeakMaps and WeakSets to
explain their observable effects on garbage collection, rather
than specifying operationally that non-live keys or members are deleted.
It separates out a definition of "live" that can be referenced from
various places. This defintion is based on earlier spec text, in
terms of whether something may be "observably referenced".

Normative: Fix the definition of liveness for WeakMap and WeakSet

---

spec/index.html
spec/weak-ref.html

Normative Optional: Add WeakRef.prototype.constructor

---

spec/abstract-jobs.html

Avoid singling out the `[[Target]]` field of a FinalizationGroup Cell record for liveness check.
It's not any more special than other un-observable internal slots.
Closes #118
Related issue: #105

Object in internal slot does not imply liveness

---

spec/finalization-group.html

FinalizationGroup instances also have a `[[IsFinalizationGroupCleanupJobActive]]` internal slot.
FinalizationGroup prototype object does not have internal slots from FinalizationGroup instances.
Fixes #137 and #143

Clarify slots on FinalizationGroup objects

---

spec/finalization-group.html

`CleanupFinalizationGroup` can result in an abrupt completion (when the user provided callback throws) so the job should be called with `?` instead of `!` to bubble the error back.

Normative: cleanupSome to re-throw CleanupFinalizationGroup errors

---

spec/abstract-jobs.html

First stab at #105. @erights @gsathya @littledan @tschneidereit please take a look.
Copy-pasting an email I sent to some folks that captures the intuition of this change:
Consider the following:
```javascript
L1: const o = {};
L2: const wr = new WeakRef(o);
L3: await 1;
L4: assert(wr.deref() === o); // this should never fail
```
One (unlikely) optimization a sufficiently smart compiler may do here is: collect `o` but remember its contents and its identity (i.e. its pointer value) between L3 and L4, and upon evaluating the comparison `wr.defer() === o` on L4, "rematerialize" the object with its original contents all the way down to its identity. If that optimization is applied, the collection of `o` between L3 and L4 may very well cause `wr.deref()` to return null.
It seems desirable to …

Amend liveness definition to mean observable object identity.

---

spec/finalization-group.html

Prevent re-entrancy by checking there is no active cleanup job in `cleanupSome`. Fixes #152

Normative: cleanupSome throw if cleanup job active

---

spec/abstract-jobs.html
spec/finalization-group.html

Guard the iterator by checking if it's still related to a FinalizationGroup object.
After the cleanup callback invocation, empty the iterator's FinalizationGroup slot to make it unusable.
Fixes #151 
Based on #158 which fixes #152.
Alternative to #153

Normative: empty iterator's [[FinalizationGroup]] slot after cleanup job

---

spec/abstract-jobs.html
spec/weak-ref.html

* Remove editor's note about definition of liveness still being under discussion, as issue #115 is now closed (as is #105, which probably should have been the issue referenced).
* Remove from editor's note a paragraph about open questions about the relationship between collection of elements in WeakMaps, WeakSets and WeakRefs.  The referenced PR comment appears to have been resolved along with issue #105.

Remove obsolete editor's notes

---

README.md
spec/abstract-jobs.html
spec/finalization-group.html

Fixes #113.
Bikesheds welcome; originally I was going to go with "holding" but it sounded weird. "heldValue" to me more properly describes a noun, and a single value.

Editorial: rename `holdings` to `heldValue`

---

spec/finalization-group.html

This note is intended to reduce ambiguity and lead to more
compatible implementations, though technically, implementations have
the freedom to make this strongly held anyway.
Closes #118

Editorial: Note to clarify that unregisterToken weakly held

---

README.md
spec/abstract-jobs.html

Editorial: Document "independent lifetime" of FinalizationGroups

---

spec/abstract-jobs.html

Fix thanks to @bakkot. Thanks to @bakkot, @kmiller68, and @waldemarhorwat for spotting it.
PTAL @erights 
Closes #179

Fix definition of liveness

---

README.md

Fix some accidentally stranded FinalizationGroup references in the README.

Rename to FinalizationRegistry in the README

---

README.md

In `makeWeakCached`, don't pass the key as an unregister token. Fixes #189.

Don't pass key as unregister token

---

README.md
spec/abstract-jobs.html
spec/finalization-registry.html

Note, there's no microtask checkpoint between all these callbacks--it's like Array.prototype.map
Landing this is blocking on some sort of consensus that it's the right way. Discussion is ongoing in #60.
Closes #155 
Closes #60

Normative: Replace finalization iterator with multiple callback calls
