tc39/proposal-weakrefs

- spec/finalization-group.html
- spec/weak-ref.html
This patch restores the state of the spec that reached consensus for Stage 2. 
cc @tschneidereit @erights
> Move constructors to the System object

- README.md
Thanks to @gsathya @domenic @tschneidereit @surma @hannespayer @littledan for the help!
> First stab at an up-to-date explainer

- README.md
> Explainer: Finish a thought

- spec/index.html
This makes the header and footer show up correctly
> Meta: Proposal metadata

- README.md
The crucial component of the comlink use case is the remote aspect; this change I think makes that more clear.  The comlink bug link was hard to read and I think the via.js link makes it more clear.
> Make explainer more specific for proxy finalization use case

- README.md
There is something to say here but I'm not sure it's worth it.  Fixes #98.
> Remove section on WeakRef and turns

- README.md
> Clarify early finalization example

- spec/weak-ref.html
> Normative: WeakRefs to a WeakMap/WeakSet key don't keep it alive

- README.md
Fix for #102.
Also adding a section explaining limitations when using WeakRef and Finalizers with some types of reference cycles.
> Fix IterableWeakMap leak and add section on cycle limitations

- README.md
See https://github.com/tc39/proposal-weakrefs/pull/106#discussion_r284133646.
> Fix up IterableWeakMap example

- README.md
Intended to address various issues at  https://github.com/w3ctag/design-reviews/issues/321
> Explainer: Clarifications based on TAG feedback

- spec/finalization-group.html
> Normative: Fix up type checks for cleanupSome

- spec/finalization-group.html
- spec/weak-ref.html
> Add @@toStringTag

- README.md
- spec/index.html
The proposal advanced to stage 3 at the June 2019 TC39 meeting.
> Update to stage 3

- README.md
Remove `#token` in the `FileStream` example and use `this` instead as a registration token.
Make clear that the unregister token is held weakly / can be collected the same way target can.
NB: In V8's current implementation (as of 7.5), this isn't true, and an token object will actually not be collected and prevent collection of the target in this case.
See #118
> Unregister token can be collected in FileStream example

- README.md
As discussed with @erights and @dtribble.
> Add Sathya as a proposal champion

- README.md
> Clarify that holdings should not refer to the weak target

- spec/finalization-group.html
Spec change based on https://github.com/tc39/proposal-weakrefs/pull/149#issuecomment-530319523
Make steps order consistent with unregister, fixes #138
> Normative: register throw if target === holdings

- README.md
Dan has done a lot of great work towards pushing this proposal over the finish line. The current champions agree that officially making him a co-champion of the proposal clearly makes sense.
CC @littledan @erights @dtribble @gsathya @codehag
> Add littledan to champions list

- README.md
https://bugzilla.mozilla.org/show_bug.cgi?id=1593698
> Update Firefox implementation status

- history/spec.md
- spec/abstract-jobs.html
- spec/finalization-group.html
- spec/weak-ref.html
> Editorial: rename [[Target]] to [[WeakRefTarget]]

- spec/abstract-jobs.html
- spec/finalization-group.html
Fixes #157
Fixes #160 
Closes #169
> Normative: The iterator may end early

- spec/abstract-jobs.html
Taken from Waldemar's suggestion from #185
> Editorial: Clarify the liveness simultaneity requirement

- spec/finalization-registry.html
This reached consensus in the April 2020 TC39.
Do folks think additional verbiage is required here?
> Normative: Make FinalizationRegistry#cleanupSome normative optional

- README.md
- spec/finalization-registry.html
This is a change that would move cleanup some into its own [repository](https://github.com/codehag/proposal-cleanup-some).
> move cleanup some into own proposal -- pending tc39 consensus

- reference.md
As it has been split into a separate proposal
> Remove cleanupSome documentation

- README.md
> Proposal is at Stage 4
